### ISSUE TITLE
Mystical Agriculture Add-On Recipes using the wrong Seed Crafting Method

### ISSUE THREAD

**Issue by MikedeKokkie** [Tntdestroyr/RC#1]
Old versions of Mystical Agriculture used so-called "Tiered Crafting Seeds" to create seeds for specific materials.
Newer versions have combined both Inferium Seeds and crafting seeds into one, dropping the crafting seeds and just using the Inferium seeds for crafting recipes. However, mods that are compatible with Mystical Agriculture add on new recipes that use the wrong Seed Crafting Method. Since the original recipes for these crafting seeds were wiped, this results in un-obtain-ability of the seeds for these add-on materials.

Seeds affected (sorted by seed Tier). All seeds are part of the Mystical Agriculture mod (according to JEI).

**Tier 2 crafting seed (7295:18) in middle needs to be replaced with Tier 2 Inferium Seed (7409)**
- Rubber Seeds (7449) 
![image](https://user-images.githubusercontent.com/45708312/92267181-b54c8f80-eee0-11ea-9b01-8048e77c6dd7.png)

**Tier 3 crafting seed (7295:19) in middle needs to be replaced with Tier 3 Inferium Seed (7410)**
- Manasteel Seeds (7495)
![image](https://user-images.githubusercontent.com/45708312/92268389-93eca300-eee2-11ea-9bd6-41bee806c6c6.png)
- Electrotine Seeds (7507)
![image](https://user-images.githubusercontent.com/45708312/92268434-a961cd00-eee2-11ea-8c28-65707977033d.png)

**Tier 4 crafting seed (7295:20) in middle needs to be replaced with Tier 4 Inferium Seed (7411)**
- Ruby Seeds (7469)
![image](https://user-images.githubusercontent.com/45708312/92268494-c5656e80-eee2-11ea-9cd6-62b8f4e60045.png)
- Sapphire Seeds (7470)
![image](https://user-images.githubusercontent.com/45708312/92268521-cf876d00-eee2-11ea-8572-65517f6f8880.png)
- Peridot Seeds (7471)
![image](https://user-images.githubusercontent.com/45708312/92268546-df9f4c80-eee2-11ea-9077-68652c0dffc9.png)
- Elementium Seeds (7496)
![image](https://user-images.githubusercontent.com/45708312/92268574-eded6880-eee2-11ea-857a-537a33a58c39.png)

**Tier 5 crafting seed (7295:21) in middle needs to be replaced with Tier 5 Inferium Seed (7412)**
- Uranium Seeds (7466)
![image](https://user-images.githubusercontent.com/45708312/92268798-53d9f000-eee3-11ea-86eb-32207b7e00f5.png)
- Terrasteel Seeds (7497)
![image](https://user-images.githubusercontent.com/45708312/92268832-5e948500-eee3-11ea-9f22-8cf23ca3eff4.png)
- Uranium 238 (7501)
![image](https://user-images.githubusercontent.com/45708312/92268853-6a804700-eee3-11ea-8d7e-44b574a71640.png)
- Iridium Seeds (7502)
![image](https://user-images.githubusercontent.com/45708312/92268880-766c0900-eee3-11ea-8820-3660d429c051.png)
- Refined Obsidian Seeds (7505)
![image](https://user-images.githubusercontent.com/45708312/92268917-81269e00-eee3-11ea-946f-9a45a729c0e5.png)

**ALTERNATIVE SOLUTION:**
Make All Tiers of Crafting Seeds available to craft again as was the case in previous versions of the mod.
https://ftbwiki.org/Base_Crafting_Seed
https://ftbwiki.org/Tier_1_Crafting_Seed
https://ftbwiki.org/Tier_2_Crafting_Seed
https://ftbwiki.org/Tier_3_Crafting_Seed
https://ftbwiki.org/Tier_4_Crafting_Seed
https://ftbwiki.org/Tier_5_Crafting_Seed

**Comment by zoeykapi** [comment]
This has already been fixed quite a while ago, are you running old scripts on your server?
