### ISSUE TITLE
New material seeds require crafting seeds isntead of inferium seeds

### ISSUE THREAD

**Issue by Pheubel** [Tntdestroyr/RC#5]
In issue #1 (Mystical Agriculture Add-On Recipes using the wrong Seed Crafting Method) the issue was raised that material seeds were using crafting seeds, which are unobtainable. Since that fix new material seeds have been added bit without the changed recipes.

### tier 4

Alumite seed (10201)
![Alumite seed](https://user-images.githubusercontent.com/22686676/93343043-536d1d80-f830-11ea-8811-b81899169665.png)

### tier 6

Nether star seed (10244)
![Nether star seed](https://user-images.githubusercontent.com/22686676/93343095-608a0c80-f830-11ea-8edb-c82640a6099f.png)

Dragon egg seed (10728)
![Dragon egg seed](https://user-images.githubusercontent.com/22686676/93343163-7566a000-f830-11ea-9fb4-a8327e27c971.png)

**Comment by MikedeKokkie** [comment]
This is my fault, because I added this new mod with these tier 6 seeds after Rachel fixed the first issue.

**Comment by MikedeKokkie** [comment]
Confirmed as working now
